version: '2'
services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  product-query-side:
    image: benwilcock/product-query-side:0.1
    container_name: product-qry-side
    depends_on:
     - rabbitmq
    ports:
      - "9090:9090"
      - "9091:9091"
  product-command-side:
    image: benwilcock/product-command-side:0.1
    container_name: product-cmd-side
    depends_on:
     - mongodb
     - rabbitmq
    ports:
      - "9000:9000"
      - "9001:9001"
