#debug: true
server:
    port: 9090
management:
    port: 9091
spring:
    application:
        name: product-query-side
        exchange: product.events.fanout.exchange
        queue: product.view.event.stream
        terminal: product.axon.terminal
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        rest:
            #base-path: api/v1
logging:
    level:
        root: INFO
        org.springframework: INFO
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.soagrowers: TRACE
    file: ./build/logs/query-side-server.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/